# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# Rajesh Ranjan <rranjan@redhat.com>, 2004-2007.
# Rajesh Ranjan <rranjan@redhat.com>, 2004-2007, 2012.
# Miroslav Suchý <msuchy@redhat.com>, 2011
# Rajesh Ranjan <rranjan@redhat.com>, 2004-2007
# Rajesh Ranjan <rranjan@redhat.com>, 2012
# Jan Dobes <jdobes@redhat.com>, 2016. #zanata
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-04-08 15:54+0200\n"
"PO-Revision-Date: 2018-03-16 11:01+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Hindi (http://www.transifex.com/projects/p/spacewalk/language/"
"hi/)\n"
"Language: hi\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Zanata 4.6.2\n"

#: ../src/up2date_client/capabilities.py:94
#, python-format
msgid ""
"This client requires the server to support %s, which the current server does "
"not support"
msgstr ""
"%s के समर्थन के लिए इस क्लाइंट को सर्वर की आवश्यकता है, जिसे मौजूदा सर्वर समर्थन नहीं देता "
"है."

#: ../src/up2date_client/config.py:162
#, python-format
msgid "%s was not found"
msgstr "%s नहीं मिला"

#: ../src/up2date_client/rpcServer.py:56
msgid "Error: Server Unavailable. Please try later."
msgstr "त्रुटि: सर्वर अनुपलब्ध. कृपया फिर कोशिश करें"

#: ../src/up2date_client/rpcServer.py:182
#, fuzzy
msgid "ERROR: can not find server CA file"
msgstr "त्रुटि: RHNS CA फाइल नहीं पा सकता है"

#: ../src/up2date_client/rpcServer.py:220
msgid "Connection aborted by the user"
msgstr "उपयोक्ता के द्वारा संबंध नष्ट किए गया है"

#: ../src/up2date_client/rpcServer.py:268
msgid "Server has refused connection due to high load"
msgstr "अधिक भार के कारण सर्वर ने संबंधन मना किया था"

#: ../src/up2date_client/up2dateErrors.py:47
#: ../src/up2date_client/up2dateErrors.py:80
#, python-format
msgid "class %s has no attribute '%s'"
msgstr "वर्ग %s के पास कोई विशेषता '%s' नहीं है"

#: ../src/up2date_client/up2dateErrors.py:107
msgid "RPM error.  The message was:\n"
msgstr "RPM त्रुटि. संदेश थाः\n"

#: ../src/up2date_client/up2dateErrors.py:114
msgid "Password error. The message was:\n"
msgstr "शब्दकूट त्रुटि. संदेश थाः\n"

#: ../src/up2date_client/up2dateErrors.py:118
msgid "RPM dependency error. The message was:\n"
msgstr "RPM अधीनता त्रुटि. संदेश था:\n"

#: ../src/up2date_client/up2dateErrors.py:128
msgid "Error communicating with server. The message was:\n"
msgstr "सर्वर के साथ संचार करने में त्रुटि. संदेश था:\n"

#: ../src/up2date_client/up2dateErrors.py:135
msgid "File Not Found: \n"
msgstr "फाइल नहीं मिलीः\n"

#: ../src/up2date_client/up2dateErrors.py:142
msgid "Delay error from server.  The message was:\n"
msgstr "सर्वर से देर होने की त्रुटि. संदेश था:\n"

#: ../src/up2date_client/up2dateErrors.py:178
msgid "Error validating data at server:\n"
msgstr "सर्वर पर आंकड़ा वैधीकृत करने में त्रुटि:\n"

#: ../src/up2date_client/up2dateErrors.py:191
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:197
msgid "The installation number is invalid"
msgstr "अधिष्ठापन संख्या अमान्य है"

#: ../src/up2date_client/up2dateErrors.py:200
msgid "Error parsing the oemInfo file at field:\n"
msgstr "इस क्षेत्र पर oemInfo फाइल के विश्लेषण करने में त्रुटि:\n"

#: ../src/up2date_client/up2dateErrors.py:227
msgid "Network error: "
msgstr "संजाल त्रुटि: "

#: ../src/up2date_client/up2dateErrors.py:295
#, fuzzy
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""
"\n"
"    आपके संगठन के पास इस Red Hat Network में इस तंत्र को पंजीकृत करने का पर्याप्त प्रबंधन "
"एंटाइटेलमेंट\n"
"    नहीं है. कृपया अपने संगठन के प्रशासक को इस त्रुटि के बारे में अधिसूचित करें. \n"
"    आप इस तंत्र को पंजीकृत करने में समर्थ होंगे यदि आपका संगठन मौजूदा एंटाइटेलमेंट को \n"
"    खाली करता है या अतिरिक्त खरीदता है. अतिरिक्त एंटाइटेलमेंट को आपके सांगठनिक \n"
"    प्रशासक के द्वारा खरीदा जाता सकता है Red Hat Network में लॉगिंग करके और \n"
"    'सदस्यता प्रबंधन' पृष्ठ को देखकर 'आपके RHN' खंड RHN के.\n"
"    \n"
"    इस त्रुटि कोड का सामान्य कारण यह हो सकता है कि आपने गलती से किसी सक्रियकरण कुंजी "
"को \n"
"    सेटअप कर लिया है जो कि सार्वभौमिक तयशुदा के रूप में सेटअप किया गया है.  यदि "
"सक्रियकरण कुंजी को \n"
"    खाता पर बतौर सार्वभौमिक तयशुदा सेटअप किया हुआ है, आप इस कुंजी को निष्क्रिय कर सकते "
"हैं और प्रबंधन एंटाइटेलमेंट की जरूरत से\n"
"    से बचने के लिए फिर कोशिश कर सकते हैं."

#, fuzzy
#~ msgid "Warning: unable to enable rhnsd with systemd"
#~ msgstr "चेतावनीः chkconfig के साथ rhnsd को समर्थ करने में असमर्थ"

#~ msgid "Warning: unable to enable rhnsd with chkconfig"
#~ msgstr "चेतावनीः chkconfig के साथ rhnsd को समर्थ करने में असमर्थ"
